// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coffee-nest/RoestereienListe.tsx": () => import("../components/mockups/coffee-nest/RoestereienListe.tsx"),
  "./components/mockups/paper-layers/Entdeckungen.tsx": () => import("../components/mockups/paper-layers/Entdeckungen.tsx"),
  "./components/mockups/paper-layers/Roastereien.tsx": () => import("../components/mockups/paper-layers/Roastereien.tsx")
};
